version: '3.8'

services:
  # HelloProject Services
  helloproject-backend:
    build: ./HelloProject/backend
    container_name: helloproject-backend
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
    volumes:
      - ./HelloProject/backend:/app
    networks:
      - helloproject-network
      - main-network

  helloproject-frontend:
    build: ./HelloProject/frontend
    container_name: helloproject-frontend
    restart: unless-stopped
    depends_on:
      - helloproject-backend
    networks:
      - helloproject-network

  helloproject-nginx:
    image: nginx:alpine
    container_name: helloproject-nginx
    restart: unless-stopped
    volumes:
      - ./HelloProject/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./HelloProject/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - helloproject-frontend
      - helloproject-backend
    networks:
      - helloproject-network
      - main-network

  # Main Nginx Reverse Proxy
  main-nginx:
    image: nginx:alpine
    container_name: main-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot_conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - helloproject-nginx
    networks:
      - main-network

  # Certbot for SSL Certificate Management
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: "no"  # Don't auto-restart, run on-demand only
    volumes:
      - certbot_conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./scripts:/scripts:ro
    networks:
      - main-network
    # No command specified - will be run manually via docker-compose run

  # Initialize certbot directory structure
  certbot-init:
    image: alpine:latest
    container_name: certbot-init
    restart: "no"
    volumes:
      - ./certbot/www:/var/www/certbot
    command: >
      sh -c "
        echo 'Creating certbot directory structure...' &&
        mkdir -p /var/www/certbot/.well-known/acme-challenge &&
        chmod -R 755 /var/www/certbot &&
        echo 'test-file' > /var/www/certbot/.well-known/acme-challenge/test &&
        echo 'Certbot directories ready for SSL validation!'
      "



  # Shared PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: shared-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - main-network

volumes:
  postgres_data:
  certbot_conf:

networks:
  helloproject-network:
    driver: bridge
  main-network:
    driver: bridge
