version: '3.8'

services:
  # HelloProject Services
  helloproject-backend:
    build: ./HelloProject/backend
    container_name: helloproject-backend
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
      - SECRET_KEY=th0shf!+4+30)gx@!krmmn5k52_g3nfdwxr_is@0uxe-ou$$!+
      - DB_NAME=helloproject_db
      - DB_USER=helloproject_user
      - DB_PASSWORD=helloproject_password
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./HelloProject/backend:/app
    networks:
      - helloproject-network
      - main-network

  helloproject-frontend:
    build: ./HelloProject/frontend
    container_name: helloproject-frontend
    restart: unless-stopped
    depends_on:
      - helloproject-backend
    networks:
      - helloproject-network

  helloproject-nginx:
    image: nginx:alpine
    container_name: helloproject-nginx
    restart: unless-stopped
    volumes:
      - ./HelloProject/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./HelloProject/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - helloproject-frontend
      - helloproject-backend
    networks:
      - helloproject-network
      - main-network

  # Main Nginx Reverse Proxy
  main-nginx:
    image: nginx:alpine
    container_name: main-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - helloproject-nginx
    networks:
      - main-network

  # Shared PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: shared-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lcw)lir^k7in0bsz0181zl_p)vwer=j1y@%5zz$wt8hywoi-q7
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - main-network

volumes:
  postgres_data:

networks:
  helloproject-network:
    driver: bridge
  main-network:
    driver: bridge
