version: '3.8'

services:
  helloproject-backend:
    build: ./backend
    container_name: helloproject-backend
    restart: unless-stopped
    environment:
      - DEBUG=False
    volumes:
      - ./backend:/app
    networks:
      - helloproject-network

  helloproject-frontend:
    build: ./frontend
    container_name: helloproject-frontend
    restart: unless-stopped
    depends_on:
      - helloproject-backend
    networks:
      - helloproject-network

  helloproject-nginx:
    image: nginx:alpine
    container_name: helloproject-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - helloproject-frontend
      - helloproject-backend
    networks:
      - helloproject-network

networks:
  helloproject-network:
    driver: bridge
